application:
  settings:
    integration:
      slack:
        bot-token: #youroauthtoken - Navigate to "Install app"
        app-token: #yourappsockettoken - Navigate to "Basic information" -> App-Level Tokens
        enabled: false
      user-email: #yourtestingmail
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ #yourdatabase
    username: #yourusername
    password: #password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true